### ISSUE TITLE
Get data by id not working null

### ISSUE THREAD

**Issue by heshamelmasry77** [miragejs/miragejs#423]
I have two end points and a **vehicles** **fixture**  I am trying to get vehicle by if but it comes undefined.

<img width="1278" alt="Screenshot 2020-04-21 at 23 35 23" src="https://user-images.githubusercontent.com/15607302/79916308-ca8cba00-8428-11ea-8433-018940035062.png">

//server.js
```

import { Server } from 'miragejs'
import vehicles from './fixtures/vehicles'

export function makeServer({ environment = 'development' } = {}) {
  const server = new Server({
    environment,
    fixtures: {
      vehicles,
    },
    seeds(server) {
      // Load all fixture data into the development db
      server.loadFixtures()
    },

    routes() {
      this.namespace = 'dashboard-api'

      this.get('/vehicles', (schema, request) => {
        console.log(schema)
        return schema.db.vehicles
      })
      this.get('/vehicles/:id', (schema, request) => {
        const vehicleId = request.params.id;
        const vehicle = schema.db.vehicles.find(vehicleId)
        console.log('MirageJS vehicle : ', vehicle)
        return {
          vehicle: vehicle,
        }
      })
    },
  })

  return server
}

```
and this is my  fixture
```

/* eslint-disable */
export default {
  data: [
    {
      type: 'vehicles',
      id: 304423,
      attributes: {
        id: 304423,
        title: 'Toyota Spacio',
        default_image: '1_inventory38500.png',
        description: 'Alloy Wheels, AM/FM Radio, CD Player, '
      },
    },
  ],
  links: {
    first: 'one',
    last: '100',
    prev: null,
    next: 'two',
  },
  meta: {
    current_page: 1,
    from: 1,
    last_page: 1812,
    path: 'some path',
    per_page: 20,
    to: 20,
    total: 36234,
  },
}

```

and here is my action in my store 
```
const actions = {
  
  getVehicleDetailsById: (context,id) => {
    return axios
      .get(`/vehicles/${id}`)
      .then((response) => {
        console.log(response)
        return response
      })
      .catch((error) => {
        console.log('error: ', error)
      })
  },
}
```

**Comment by samselikoff** [comment]
I would define a model and use the JSONAPISerializer, since it looks like that's the API format you're expecting.

Here's a REPL: https://miragejs.com/repl/?config=Ly8gVHJ5IGJvdGggL3ZlaGljbGVzIGFuZCAvdmVoaWNsZXMvMSBvdmVyIHRoZXJlID0%2BCmltcG9ydCB7IFNlcnZlciwgTW9kZWwsIEpTT05BUElTZXJpYWxpemVyIH0gZnJvbSAnbWlyYWdlanMnCgpleHBvcnQgZGVmYXVsdCBuZXcgU2VydmVyKHsKICBzZXJpYWxpemVyczogewogICAgYXBwbGljYXRpb246IEpTT05BUElTZXJpYWxpemVyCiAgfSwKICAKICBtb2RlbHM6IHsKICAgIHZlaGljbGU6IE1vZGVsCiAgfSwKICAKICBmaXh0dXJlczogewogICAgdmVoaWNsZXM6IFsKICAgICAgewogICAgICAgIHR5cGU6ICd2ZWhpY2xlcycsCiAgICAgICAgdGl0bGU6ICdUb3lvdGEgU3BhY2lvJywKICAgICAgICBkZWZhdWx0SW1hZ2U6ICcxX2ludmVudG9yeTM4NTAwLnBuZycsCiAgICAgICAgZGVzY3JpcHRpb246ICdBbGxveSBXaGVlbHMsIEFNL0ZNIFJhZGlvLCBDRCBQbGF5ZXIsICcKICAgICAgfQogICAgXSwKICB9LAogIAogIHNlZWRzKHNlcnZlcikgewogICAgc2VydmVyLmxvYWRGaXh0dXJlcygpCiAgfSwKCiAgcm91dGVzKCkgewogICAgdGhpcy5uYW1lc3BhY2UgPSAnZGFzaGJvYXJkLWFwaScKCiAgICB0aGlzLmdldCgnL3ZlaGljbGVzJywgZnVuY3Rpb24oc2NoZW1hLCByZXF1ZXN0KSB7CiAgICAgIHJldHVybiBzY2hlbWEudmVoaWNsZXMuYWxsKCkKICAgIH0pCiAgICAKICAgIHRoaXMuZ2V0KCcvdmVoaWNsZXMvOmlkJywgZnVuY3Rpb24oc2NoZW1hLCByZXF1ZXN0KSB7CiAgICAgIGNvbnN0IHZlaGljbGVJZCA9IHJlcXVlc3QucGFyYW1zLmlkOwogICAgICByZXR1cm4gc2NoZW1hLnZlaGljbGVzLmZpbmQodmVoaWNsZUlkKQogICAgfSkKICB9LAp9KQ%3D%3D&url=%2Fdashboard-api%2Fvehicles%2F1

**Comment by heshamelmasry77** [comment]
> I would define a model and use the JSONAPISerializer, since it looks like that's the API format you're expecting.
> 
> [Here's a REPL](https://miragejs.com/repl/?config=Ly8gVHJ5IGJvdGggL3ZlaGljbGVzIGFuZCAvdmVoaWNsZXMvMSBvdmVyIHRoZXJlID0%2BCmltcG9ydCB7IFNlcnZlciwgTW9kZWwsIEpTT05BUElTZXJpYWxpemVyIH0gZnJvbSAnbWlyYWdlanMnCgpleHBvcnQgZGVmYXVsdCBuZXcgU2VydmVyKHsKICBzZXJpYWxpemVyczogewogICAgYXBwbGljYXRpb246IEpTT05BUElTZXJpYWxpemVyCiAgfSwKICAKICBtb2RlbHM6IHsKICAgIHZlaGljbGU6IE1vZGVsCiAgfSwKICAKICBmaXh0dXJlczogewogICAgdmVoaWNsZXM6IFsKICAgICAgewogICAgICAgIHR5cGU6ICd2ZWhpY2xlcycsCiAgICAgICAgdGl0bGU6ICdUb3lvdGEgU3BhY2lvJywKICAgICAgICBkZWZhdWx0SW1hZ2U6ICcxX2ludmVudG9yeTM4NTAwLnBuZycsCiAgICAgICAgZGVzY3JpcHRpb246ICdBbGxveSBXaGVlbHMsIEFNL0ZNIFJhZGlvLCBDRCBQbGF5ZXIsICcKICAgICAgfQogICAgXSwKICB9LAogIAogIHNlZWRzKHNlcnZlcikgewogICAgc2VydmVyLmxvYWRGaXh0dXJlcygpCiAgfSwKCiAgcm91dGVzKCkgewogICAgdGhpcy5uYW1lc3BhY2UgPSAnZGFzaGJvYXJkLWFwaScKCiAgICB0aGlzLmdldCgnL3ZlaGljbGVzJywgZnVuY3Rpb24oc2NoZW1hLCByZXF1ZXN0KSB7CiAgICAgIHJldHVybiBzY2hlbWEudmVoaWNsZXMuYWxsKCkKICAgIH0pCiAgICAKICAgIHRoaXMuZ2V0KCcvdmVoaWNsZXMvOmlkJywgZnVuY3Rpb24oc2NoZW1hLCByZXF1ZXN0KSB7CiAgICAgIGNvbnN0IHZlaGljbGVJZCA9IHJlcXVlc3QucGFyYW1zLmlkOwogICAgICByZXR1cm4gc2NoZW1hLnZlaGljbGVzLmZpbmQodmVoaWNsZUlkKQogICAgfSkKICB9LAp9KQ%3D%3D&url=%2Fdashboard-api%2Fvehicles%2F1). Try a GET to `/dashboard-api/vehicles/1` and `/dashboard-api/vehicles`.

I tried to use it with my data and it wasn't working too so i wrote this :
 ```
this.get('/vehicle/:id', (schema, request) => {
        const vehicleId = request.params.id
        const vehiclesData = schema.db.vehicles[0].data
        var vehicle = vehiclesData.find((item) => item.id === Number(vehicleId))
        return vehicle
      })
```

**Comment by samselikoff** [comment]
Yeah so you're working with the underlying `db` which is just the lowest level data store. You can do that but you won't be able to take advantage of the ORM and Serializer layer, which can do a lot of the formatting work for you.

Take a look at the ORM guide if you want to learn more: https://miragejs.com/docs/main-concepts/orm/

**Comment by samselikoff** [comment]
Feel free to post another example if you're having trouble getting something working!
