### ISSUE TITLE
Remove test environment from React develop an app

### ISSUE THREAD

**Issue by christian-cuna** [miragejs/miragejs#540]
The [React develop an app](https://miragejs.com/quickstarts/react/develop-an-app/) quickstart uses the `test` environment but includes a `seeds` method. As the `seeds` method is not called on the `test` environment, it's quite confusing for people starting to use the library why the method is not called (you have to look into the [testing/application-tests/#the-test-environment](https://miragejs.com/docs/testing/application-tests/#the-test-environment) to discover this). 

Code from the quickstart:

``` javascript
// src/server.js
import { Server, Model } from "miragejs"

export function makeServer({ environment = "test" } = {}) {
  let server = new Server({
    environment,

    models: {
      user: Model,
    },

    seeds(server) {
      server.create("user", { name: "Bob" })
      server.create("user", { name: "Alice" })
    },

    routes() {
      this.namespace = "api"

      this.get("/users", (schema) => {
        return schema.users.all()
      })
    },
  })

  return server
}
```

**Comment by samselikoff** [comment]
Oof 😣 Sorry you hit that, that is quite confusing!

I think we should update the call to `makeServer` to pass in the environment: `makeServer({ environment: 'development' })`

The reason we default to test is because in most projects `makeServer` will be called once for dev in `index.js`, and many times across various test files.

**Comment by samselikoff** [comment]
https://github.com/miragejs/site/commit/da20ea50baf0cd7ceb07cd0bc379283f7aba6f8d fixes
