### ISSUE TITLE
Server handlers and factories

### ISSUE THREAD

**Issue by thec0keman** [miragejs/miragejs#632]
Is there a way to invoke factories from within a server handler?  The use case is that it would be nice to have a POST endpoint that uses the factory as default values, and merges the normalized attributes from the request onto this.

Or is this going against the design?

Thanks!

**Comment by thec0keman** [comment]
Or perhaps another way to put it: what is the best practice around the server returning default / computed attributes?  With factories this is trivial, but since the model's themselves are schemaless, it seems like the only alternative would be to append these in the serializer.  But adding default / computed props doesn't seem like a good responsibility for the serializer.

**Comment by samselikoff** [comment]
Yeah folks have asked for this – we really need to add the concept of model defaults that are invoked whenever `schema.create` is used.

Factories are really intended for seeding initial data, since route handlers will mostly be using data from the client (i.e. data from request.requestBody.)

We really need something like, the default value for `admin` is `false` on a User model. Right now if you wanted that sort of logic in both the factory and in route handlers, I think the best way is to make a function that you can share in both places, something like

```js
function userDefaults() {
  return { admin: false };
}

createServer({
  factories: {
    user: Factory.extend({
      afterCreate(user, server) {
        user.update(userDefaults());
      },
    }),
  },

  routes() {
    this.post("/users", function (schema, request) {
      let attrs = this.normalizedRequestAttrs();

      return createUser({ ...userDefaults(), ...attrs });
    });
  },
});
```

You might have to play with the logic in afterCreate to have it play nice with other attrs you may define. Let me know if you have more questions if you try this out.

**Comment by thec0keman** [comment]
Thanks, that is helpful
