### ISSUE TITLE
How to model many-to-many through associations ?

### ISSUE THREAD

**Issue by clementoriol** [miragejs/miragejs#757]
In rails, there's the [has_many :through association](https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association) that allows to model a many-to-many association through another model.

Is there a way to achieve the same result with miragejs ?

Let's say I have the same model as in the rails docs link: 
```
{
  physician: Model.extend({
    appointments: hasMany("appointment"),
  }),
  appointment: Model.extend({
    physician: belongsTo("physician"),
    patient: belongsTo("patient"),
  }),
  patient: Model.extend({
    appointments: hasMany("appointment"),
  })
}
```

and want my `/physician/:id` route response to embed `patients` ?
How could I achieve that ?

a "through" option would be great for hasMany, but that currently doesn't exist. How would you currently handle this ?

**Comment by clementoriol** [comment]
2 approaches I've found, poking around, to achieve what I want.

- using a json response : https://miragejs.com/repl/v2/4225bfc355
- using .attrs : https://miragejs.com/repl/v2/99929f3861

Would love some feedback on this :)

**Comment by samselikoff** [comment]
Sorry been delayed on this!

You actually can use `this.serialize` you just need to use `function` instead of a fat arrow because of context. Silly but kinda the API we're stuck with for now: https://miragejs.com/repl/v2/fc81a7e098

You could also create a model-specific Serializer and [override the `serialize`](https://miragejs.com/api/classes/serializer/#serialize) method, so your route handlers can still just return models: https://miragejs.com/repl/v2/a161cc494a. Can tidy this one up or explain further if you want to go down this route!

**Comment by clementoriol** [comment]
Thank you for the examples, this is way more clear.

I got tripped up on the `this.serialize` thing because I thought this was referencing the server, that I was passing manually to my  routes function. This clears things up :)
